const data = [
  {
    url: "https://via.placeholder.com/600/92c952",
    channel: "1",
    song: "accusamus beatae ad facilis cum similique qui sunt",
    likes: "3",
    messages: "200",
    description: "repellendus sunt dolores architecto voluptatum",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/771796",
    channel: "2",
    song: "reprehenderit est deserunt velit ipsam",
    likes: "3",
    messages: "200",
    description: "et porro tempora",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/24f355",
    channel: "3",
    song: "officia porro iure quia iusto qui ipsa ut modi",
    likes: "3",
    messages: "200",
    description:
      "laboriosam mollitia et enim quasi adipisci quia provident illum",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/d32776",
    channel: "4",
    song: "culpa odio esse rerum omnis laboriosam voluptate repudiandae",
    likes: "3",
    messages: "200",
    description: "qui ullam ratione quibusdam voluptatem quia omnis",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/f66b97",
    channel: "5",
    song: "natus nisi omnis corporis facere molestiae rerum in",
    likes: "3",
    messages: "200",
    description: "illo expedita consequatur quia in",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/56a8c2",
    channel: "6",
    song: "accusamus ea aliquid et amet sequi nemo",
    likes: "3",
    messages: "200",
    description: "quo adipisci enim quam ut ab",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/b0f7cc",
    channel: "7",
    song: "officia delectus consequatur vero aut veniam explicabo molestias",
    likes: "3",
    messages: "200",
    description: "molestiae perspiciatis ipsa",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/54176f",
    channel: "8",
    song: "aut porro officiis laborum odit ea laudantium corporis",
    likes: "3",
    messages: "200",
    description: "illo est ratione doloremque quia maiores aut",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/51aa97",
    channel: "9",
    song: "qui eius qui autem sed",
    likes: "3",
    messages: "200",
    description: "vero rerum temporibus dolor",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/810b14",
    channel: "10",
    song: "beatae et provident et ut vel",
    likes: "3",
    messages: "200",
    description: "ipsa repellendus fugit nisi",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/1ee8a4",
    channel: "11",
    song: "nihil at amet non hic quia qui",
    likes: "3",
    messages: "200",
    description: "et doloremque nulla",

    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/66b7d2",
    channel: "12",
    song:
      "mollitia soluta ut rerum eos aliquam consequatur perspiciatis maiores",
    likes: "3",
    messages: "200",
    description: "ab voluptatum amet voluptas",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/197d29",
    channel: "13",
    song: "repudiandae iusto deleniti rerum",
    likes: "3",
    messages: "200",
    description: "accusamus eos facilis sint et aut voluptatem",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/f9cee5",
    channel: "15",
    song: "harum dicta similique quis dolore earum ex qui",
    likes: "3",
    messages: "200",
    description: "quo laboriosam deleniti aut qui",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/fdf73e",
    channel: "16",
    song: "iusto sunt nobis quasi veritatis quas expedita voluptatum deserunt",
    likes: "3",
    messages: "200",
    description: "dolorum est consequatur ea mollitia in culpa",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/9c184f",
    channel: "17",
    song: "natus doloribus necessitatibus ipsa",
    likes: "3",
    messages: "200",
    description: "molestiae ipsa aut voluptatibus pariatur dolor nihil",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/1fe46f",
    channel: "18",
    song: "laboriosam odit nam necessitatibus et illum dolores reiciendis",
    likes: "3",
    messages: "200",
    description: "ullam nobis libero sapiente ad optio sint",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/56acb2",
    channel: "19",
    song: "perferendis nesciunt eveniet et optio a",
    likes: "3",
    messages: "200",
    description: "suscipit repellat esse quibusdam voluptatem incidunt",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/8985dc",
    channel: "20",
    song:
      "assumenda voluptatem laboriosam enim consequatur veniam placeat reiciendis error",
    likes: "3",
    messages: "200",
    description: "distinctio vitae autem nihil ut molestias quo",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/5e12c6",
    channel: "21",
    song: "ad et natus qui",
    likes: "3",
    messages: "200",
    description: "et itaque necessitatibus maxime molestiae qui quas velit",
    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/4e557c",
    likes: "2",
    channel: "63",
    likes: "3",
    messages: "200",
    description: "fugiat veniam minus",

    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/cd5a92",
    likes: "2",
    channel: "64",
    likes: "3",
    messages: "200",
    description: "quis ut nam facilis et officia qui",

    shares: "500",
  },
  {
    url: "https://via.placeholder.com/600/149540",
    likes: "2",
    channel: "65",
    likes: "3",
    messages: "200",
    description: "delectus aut autem",
  },
];
export default data;
